name: calendar_day_view
description: This package is dedicated to calendar day view. This is a complement to calendar to make your app better
version: 3.3.0
homepage: https://github.com/samderlust/calendar_day_view

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  linked_scroll_controller: ^0.2.0
  timezone: ^0.9.2
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
topics:
  - calendar
  - calendar-day-view
  - calendar-view
  - day-view
